##### COLOR PARAMETERS #####
set -g @copy_mode_border_color colour130 #orange
set -g @copy_mode_highlight_text_color colour215 #orange    
set -g @copy_mode_highlight_bg_color colour130 #orange

set -g @accent_secondary_color colour141 #lavender
set -g @aaccent_prefix_color colour129 #bright purple (prefix indicator)
set -g @accent_background_color colour237 #dark gray (status bar background)
set -g @accent_secondary_background_color colour239 #medium gray (inactive window background)
set -g @accent_foreground colour231 #white (text on status bar)


##### PREFIX #####
unbind C-b
set -g prefix C-a
bind C-a send-prefix

##### BASICS #####
set -g mouse on
setw -g mode-keys emacs
set -g history-limit 100000
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows off

##### WINDOWS #####
bind c new-window -a
bind -n S-Left previous-window
bind -n S-Right next-window

##### PANES #####
# Preferred splitting
unbind '"'
unbind %
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

##### COPY / SCROLL #####
unbind -T copy-mode MouseDragEnd1Pane
bind -T copy-mode MouseDragEnd1Pane send -X copy-selection
bind s copy-mode \; send-keys '?'

# Make copy mode more obvious with a different color scheme
set -g mode-style "fg=#{@copy_mode_highlight_text_color},bg=#{@copy_mode_highlight_bg_color}"

set -g pane-border-style "#{?pane_in_mode,fg=#{@copy_mode_border_color},fg=#{@accent_foreground}}"
set -g pane-active-border-style "#{?pane_in_mode,fg=#{@copy_mode_border_color},fg=#{@accent_secondary_color}}"
set -g pane-border-format "#{?pane_in_mode,#[fg=#{@copy_mode_border_color},bold] COPY #[default],}#{pane_index} #{pane_title}"
##### STATUS BAR ########
set -g status on
set -g status-interval 5
set -g status-style "bg=#{@accent_background_color},fg=#{@accent_foreground}"
set -g status-left-length 30
set -g status-right-length 150

# Left: session name with small visual indicator if prefix is pressed
set -g status-left "\
#[fg=colour7,bg=colour241]#{?client_prefix,#[bg=#{@aaccent_prefix_color}],} ❐ #S \
#[fg=colour241,bg=#{@accent_background_color}]#{?client_prefix,#[fg=#{@aaccent_prefix_color}],}#{?window_zoomed_flag, 🔍,}"

# Right: date/time with visual separators
set -g status-right "\
#[fg=#{@accent_foreground},bg=#{@accent_background_color}]  %b %d %y\
#[fg=#{@accent_foreground}]  %H:%M \
#[fg=#{@accent_foreground},bg=#{@accent_background_color}]"

# Inactive windows, with visual separators and current window index/name displayed
set-window-option -g window-status-format "\
#[fg=#{@accent_background_color},bg=#{@accent_secondary_background_color},noitalics]\
#[fg=#{@accent_foreground},bg=#{@accent_secondary_background_color}] #I \
#[fg=#{@accent_foreground},bg=#{@accent_secondary_background_color}] #W \
#[fg=#{@accent_secondary_background_color},bg=#{@accent_background_color}]"

# Active window
set-window-option -g window-status-current-format "\
#[fg=#{@accent_background_color},bg=#{@accent_secondary_color}]\
#[fg=#{@accent_background_color},bg=#{@accent_secondary_color}] #I \
#[fg=#{@accent_background_color},bg=#{@accent_secondary_color},bold] #W \
#[fg=#{@accent_secondary_color},bg=#{@accent_background_color}]"

# Activity alert
set-window-option -g window-status-activity-style "bg=#{@accent_background_color},fg=colour248"

# Bell alert
set-window-option -g window-status-bell-style "bg=#{@aaccent_prefix_color},fg=colour235"

##### VISUALS #####
set -g pane-border-style "fg=#{@accent_foreground}"
set -g message-style "bg=#{@accent_background_color},fg=#{@accent_foreground}"

##### SSH FRIENDLY SETTINGS #####
set -g remain-on-exit on
set -g automatic-rename off
set -g allow-rename off
set -g history-limit 200000
set -g pane-border-status top
set -g pane-border-format "#{pane_index} #{pane_title}"
